### ISSUE TITLE
dvmhost 3.0-dev P25 Site Trunking

### ISSUE THREAD

**Issue by ceb515** [DVMProject/dvmhost#18]
Radios are showing as site trunking while dvmhost is connected to FNE. Verified connectivity to FNE as ADJ STS BCAST messages are passing in both directions.

**Comment by gatekeep** [comment]
Can you retest with commit 5813bcb9156cda7fa55dd5ff84aa5c70a9c58cf0? This should resolve the flag not being set.

**Comment by ceb515** [comment]
Latest commit fixes issue. Closing
