### ISSUE TITLE
Host transmitting via HS when not suppose to.

### ISSUE THREAD

**Issue by kjl13** [DVMProject/dvmhost#3]
I have a DVM host setup with a hotspot running on a PI. I have duplex set to false and hang time set to 0, but even after changing those settings and restarting my DVM will still transmit once it stops receiving. Below you can see my SDR picking up my radio transmitting and then the hotspot transmitting.
![image](https://user-images.githubusercontent.com/10225883/155009690-9f218164-e848-42a4-8183-b179fb3052a7.png)

**Comment by gatekeep** [comment]
Please retest with newer builds when able; there was a issue with TDULC Call Termination (which was only intended on being transmitted in duplex mode) being transmitted in simplex operational mode. [Though I'm not sure why in my initial tests this didn't happen, none-the-less tests done before this commit saw the issue.]
