### ISSUE TITLE
FNE Connection seems to time out on newest commit

### ISSUE THREAD

**Issue by carcarjg** [DVMProject/dvmhost#36]
[CC-2023-07-16.log](https://github.com/DVMProject/dvmhost/files/12063123/CC-2023-07-16.log)
[VC1-2023-07-16.log](https://github.com/DVMProject/dvmhost/files/12063124/VC1-2023-07-16.log)

FNE Site
[fnerouter-20230715.log](https://github.com/DVMProject/dvmhost/files/12063126/fnerouter-20230715.log)
(FNE log was trimmed bc of size, morning was removed)

**Comment by gatekeep** [comment]
Is this paired with the latest code for the FNE as well?

**Comment by gatekeep** [comment]
> > Is this paired with the latest code for the FNE as well?
> 
> Not yet, Guessing incompatibility?

Its possible, yes. The latest code changes clean up the network protocol making it a bit more concise, those changes may not be entirely backward compatible, causing the connection drop issues you are seeing (*possibly*). I have an entire environment running in test with latest code across the board, and have had no issues with dropped communications to the conference bridge FNE or FNE2.

**Comment by gatekeep** [comment]
If you can, can you collect the Git hashes of your dvmhosts and the dvmfne2?
