### ISSUE TITLE
Unhandled Exception For REST API Resets Causes Segfaults

### ISSUE THREAD

**Issue by faultywarrior** [DVMProject/dvmhost#40]
If a remote REST peer sends a reset packet; DVMHost fails to gracefully handle the exception and instead segfaults, simply returning the upstream error from the Linux IP stack as seen in the screenshot below. ![image](https://github.com/DVMProject/dvmhost/assets/25770089/3ba91bae-f3d2-45ee-b725-337a9b78589a)

**Comment by gatekeep** [comment]
Try 58780d9 and see if this happens again; if so reopen this issue.
