### ISSUE TITLE
TGIDs and RIDs not updating at specified intervals

### ISSUE THREAD

**Issue by thenumbers1** [DVMProject/dvmhost#44]
After adding a new RID to the FNE whitelist, I noticed that DVM still throws Reg Refused at the radio, even after the two-minute update setting for RID ACL updates. The same goes for TGIDs; no update after the specified interval. I am unsure if this is a host issue or an FNE issue, but I figured I'd open the issue here.

**Comment by gatekeep** [comment]
I'm gonna close this here, re-report this on the dvmfne2 project, please. RID/TGID ACL pushes happen from it and are not done on the host. Additionally make sure you are using the latest dvmfne2, I know @W3AXL fixed an issue with this.
