### ISSUE TITLE
Traffic from SU on DVRS repeater/hotspot causes Invalid LC errors on DFSI host

### ISSUE THREAD

**Issue by jsb5151** [DVMProject/dvmhost#64]
Use case:

SU (APX) in DVRS mode -> DVRS Host -> FNE -> DFSI Host -> Quantar

Calls originating from a DVRS Host create "Invalid LC error" messages and causes audio cutouts on DFSI repeaters.  Per GK, this is because the internal routines are unable to properly handle the inbound RFSS_STS_BCAST LC frames.

```
E: 2024-07-25 16:22:33.789 (P25) LC::decodeLC(), unknown LC value, mfId = $00, lco = $23
W: 2024-07-25 16:22:33.789 (MODEM) P25, LDU1 (Logical Link Data Unit 1), undecodable LC
```

**Comment by gatekeep** [comment]
Please retest and let me know; this should be resolved.
