### ISSUE TITLE
Rolling CC

### ISSUE THREAD

**Issue by carcarjg** [DVMProject/dvmhost#9]
Add the ability to have mode change from CC to VC at a set interval. Would need to be coordinated with FNE?

Could also put in HS number and have it change daily with all HSs waiting until an internal counter rolls to them, Would need for all HSs to start at the same time

Or have the HS's assigned days of the week (HS1 = M,W,F HS2 = T,T,S HS3 = Sunday)

I think the last option would be the best unless we get the fabled site controller software

**Comment by carcarjg** [comment]
Also added to FNE

**Comment by gatekeep** [comment]
This would be a feature implemented at the soon-to-exist STC (Site Trunk Controller) FNE application, and not at the host.

**Comment by carcarjg** [comment]
> This would be a feature implemented at the soon-to-exist STC (Site Trunk Controller) FNE application, and not at the host.

Epic
